---
- name: CHECKING IP ROUTE
  hosts: routers
  become_method: enable
  gather_facts: false
  connection: network_cli

  tasks:
    - name: PRINTING IP INTERFACES
      ios_command:
        commands:
          - show ip route
      register: config

    - name: SAVE OUTPUT TO ./IOS_CONFIGS/
      copy:
        content: "{{config.stdout[0]}}"
        dest: "IOS CONFIGS/show_iproute_{{inventory_hostname}}.txt"